### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by jgx0** [Optixal/dotfiles#2]
I love your neon midnight rice. How would I install it on my system? I can edit configs, etc.

**Comment by KebabLord** [comment]
for color scheme you can use pywal with wallpaper's path. 
```
pip3 install pywal
wal -i ~/path/to/wallpaper
```
the wallpaper:
![a](https://user-images.githubusercontent.com/24779257/98154255-915bf900-1ee5-11eb-959c-05ff730eb9b9.jpeg)
